=== cw-dvr8/JSON-validation-schemas/validation_schemas/psychENCODE_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id":"http://example.com/psychENCODE_schema.json",
  "title": "annotations",
  "description": "Validates PsychENCODE file annotations",
  "type": "object",
  "properties": {
    "consortium": {
      "$ref": "sageCommunity.json#/definitions/consortium"
    },
    "grant": {
      "$ref": "neuro.json#/definitions/grant"
    },
    "study": {
      "$ref": "neuro.json#/definitions/study"
    },
    "group": {
      "$ref": "sageCommunity.json#/definitions/group"
    },
    "investigatorName": {
      "$ref": "clinicalData.json#/definitions/investigatorName"
    },
    "individualID": {
      "$ref": "experimentalData.json#/definitions/individualID"
    },
    "individualIdSource": {
      "$ref": "experimentalData.json#/definitions/individualIdSource"
    },
    "species": {
      "$ref": "experimentalData.json#/definitions/species"
    },
    "reportedGender": {
      "$ref": "clinicalData.json#/definitions/reportedGender"
    },
    "postmortem": {
      "$ref": "clinicalData.json#/definitions/postmortem"
    },
    "sex": {
      "$ref": "experimentalData.json#/definitions/sex"
    },
    "race": {
      "$ref": "clinicalData.json#/definitions/race"
    },
    "raceDetail": {
      "$ref": "clinicalData.json#/definitions/raceDetail"
    },
    "genotypeInferredAncestry": {
      "$ref": "clinicalData.json#/definitions/genotypeInferredAncestry"
    },
    "IQ": {
      "$ref": "clinicalData.json#/definitions/IQ"
    },
    "BMI": {
      "$ref": "clinicalData.json#/definitions/BMI"
    },
    "primaryDiagnosis": {
      "$ref": "clinicalData.json#/definitions/primaryDiagnosis"
    },
    "primaryDiagnosisDetail": {
      "$ref": "clinicalData.json#/definitions/primaryDiagnosisDetail"
    },
    "otherDiagnosis": {
      "$ref": "clinicalData.json#/definitions/otherDiagnosis"
    },
    "otherDiagnosisDetail": {
      "$ref": "clinicalData.json#/definitions/otherDiagnosisDetail"
    },
    "familyHistory": {
      "$ref": "clinicalData.json#/definitions/familyHistory"
    },
    "ageOnset": {
      "$ref": "clinicalData.json#/definitions/ageOnset"
    },
    "neuropathDescription" : {
      "$ref": "clinicalData.json#/definitions/neuropathDescription"
    },
    "dementia": {
      "$ref": "clinicalData.json#/definitions/dementia"
    },
    "CDR": {
      "$ref": "clinicalData.json#/definitions/CDR"
    },
    "braak": {
      "$ref": "clinicalData.json#/definitions/braak"
    },
    "otherMedicalDx": {
      "$ref": "clinicalData.json#/definitions/otherMedicalDx"
    },
    "otherMedicalDetail": {
      "$ref": "clinicalData.json#/definitions/otherMedicalDetail"
    },
    "deathAge": {
      "$ref": "clinicalData.json#/definitions/deathAge"
    },
    "deathAgeUnits": {
      "$ref": "clinicalData.json#/definitions/deathAgeUnits"
    },
    "causeDeath": {
      "$ref": "clinicalData.json#/definitions/causeDeath"
    },
    "deathManner": {
      "$ref": "clinicalData.json#/definitions/deathManner"
    },
    "postmortemTox": {
      "$ref": "clinicalData.json#/definitions/postmortemTox"
    },
    "postmortemToxSource": {
      "$ref": "clinicalData.json#/definitions/postmortemToxSource"
    },
    "medRecordTox": {
      "$ref": "clinicalData.json#/definitions/medRecordTox"
    },
    "organ": {
      "$ref": "experimentalData.json#/definitions/organ"
    },
    "PMICertain": {
      "$ref": "clinicalData.json#/definitions/PMICertain"
    },
    "PMI": {
      "$ref": "neuro.json#/definitions/PMI"
    },
    "pH": {
      "$ref": "neuro.json#/definitions/pH"
    },
    "organWeight": {
      "$ref": "clinicalData.json#/definitions/organWeight"
    },
    "organRIN": {
      "$ref": "clinicalData.json#/definitions/organRIN"
    },
    "yearAutopsy": {
      "$ref": "clinicalData.json#/definitions/yearAutopsy"
    },
    "specimenID": {
      "$ref": "experimentalData.json#/definitions/specimenID"
    },
    "tissue": {
      "$ref": "experimentalData.json#/definitions/tissue"
    },
    "cellType": {
      "$ref": "experimentalData.json#/definitions/cellType"
    },
    "nucleicAcidSource": {
      "$ref": "ngs.json#/definitions/nucleicAcidSource"
    },
    "BrodmannArea": {
      "$ref": "neuro.json#/definitions/BrodmannArea"
    },
    "reprogrammedCellType": {
      "$ref": "clinicalData.json#/definitions/reprogrammedCellType"
    },
    "terminalDifferentiationPoint": {
      "$ref": "experimentalData.json#/definitions/terminalDifferentiationPoint"
    },
    "passage": {
      "$ref": "clinicalData.json#/definitions/passage"
    },
    "assay": {
      "$ref": "experimentalData.json#/definitions/assay"
    },
    "assayTarget": {
      "$ref": "experimentalData.json#/definitions/assayTarget"
    },
    "libraryID": {
      "$ref": "clinicalData.json#/definitions/libraryID"
    },
    "isStranded": {
      "$ref": "ngs.json#/definitions/isStranded"
    },
    "RIN": {
      "$ref": "clinicalData.json#/definitions/RIN"
    },
    "readStrandOrigin": {
      "$ref": "ngs.json#/definitions/readStrandOrigin"
    },
    "readLength": {
      "$ref": "ngs.json#/definitions/readLength"
    },
    "platform": {
      "$ref": "experimentalData.json#/definitions/platform"
    },
    "runType": {
      "$ref": "ngs.json#/definitions/runType"
    },
    "libraryPrep": {
      "$ref": "ngs.json#/definitions/libraryPrep"
    },
    "libraryPreparationMethod": {
      "$ref": "ngs.json#/definitions/libraryPreparationMethod"
    },
    "fileFormat": {
      "$ref": "sageCommunity.json#/definitions/fileFormat"
    },
    "referenceSet": {
      "$ref": "curatedData.json#/definitions/referenceSet"
    },
    "readPair": {
      "$ref": "ngs.json#/definitions/readPair"
    },
    "rRNARate": {
      "$ref": "clinicalData.json#/definitions/rRNARate"
    },
    "meanCoverage": {
      "$ref": "clinicalData.json#/definitions/meanCoverage"
    },
    "meanGCContent": {
      "$ref": "clinicalData.json#/definitions/meanGCContent"
    },
    "percentAligned": {
      "$ref": "clinicalData.json#/definitions/percentAligned"
    },
    "totalReads": {
      "$ref": "clinicalData.json#/definitions/totalReads"
    },
    "mappedReads": {
      "$ref": "clinicalData.json#/definitions/mappedReads"
    },
    "FRiP": {
      "$ref": "clinicalData.json#/definitions/FRiP"
    },
    "biologicalReplicate": {
      "$ref": "clinicalData.json#/definitions/biologicalReplicate"
    },
    "isogenicReplicate": {
      "$ref": "clinicalData.json#/definitions/isogenicReplicate"
    },
    "anisogenicReplicate": {
      "$ref": "clinicalData.json#/definitions/anisogenicReplicate"
    },
    "technicalReplicate": {
      "$ref": "clinicalData.json#/definitions/technicalReplicate"
    },
    "sequencingReplicate": {
      "$ref": "clinicalData.json#/definitions/sequencingReplicate"
    }
  },
  "required": [
    "consortium",
    "grant",
    "study",
    "group",
    "investigatorName",
    "individualID",
    "individualIdSource",
    "species",
    "reportedGender",
    "postmortem",
    "organ",
    "specimenID",
    "tissue",
    "cellType",
    "nucleicAcidSource",
    "reprogrammedCellType",
    "terminalDifferentiationPoint",
    "passage",
    "assay",
    "libraryID",
    "isStranded",
    "RIN",
    "readLength",
    "platform",
    "runType",
    "libraryPrep",
    "libraryPreparationMethod",
    "fileFormat",
    "referenceSet",
    "readPair",
    "biologicalReplicate",
    "isogenicReplicate",
    "anisogenicReplicate",
    "technicalReplicate",
    "sequencingReplicate"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "species": {
            "const": "Human"
          }
        }
      },
      "then": {
        "required": ["sex", "race", "raceDetail", "genotypeInferredAncestry", "IQ", "BMI",
                     "primaryDiagnosis", "primaryDiagnosisDetail", "otherDiagnosis", "familyHistory",
                     "ageOnset", "neuropathDescription", "dementia", "otherMedicalDx"]
      }
    },
    {
      "if": {
        "allOf": [
          {
            "properties": {
              "species": {
                "const": "Human"
              },
              "otherDiagnosis": {
                "not": {"const": "None"}
              }
            },
	    "required": ["otherDiagnosis"]
          }
        ]
      },
      "then": {
        "required": ["otherDiagnosisDetail"]
      }
    },
    {
      "if": {
        "allOf": [
          {
            "properties": {
              "species": {
                "const": "Human"
              },
	      "dementia": {
                "const": "True"
              }
            },
            "required": ["dementia"]
          }
        ]
      },
      "then": {
        "required": ["CDR", "braak"]
      }
    },
    {
      "if": {
        "allOf": [
          {
            "properties": {
              "species": {
                "const": "Human"
              },
	      "otherMedicalDx": {
                "not": {"const": "None"}
              }
            },
	    "required": ["otherMedicalDx"]
          }
        ]
      },
      "then": {
        "required": ["otherMedicalDetail"]
      }
    },
    {
      "if": {
        "allOf": [
          {
            "properties": {
              "species": {
                "const": "Human"
              },
              "postmortem": {
                "const": "True"
              }
            },
	    "required": ["postmortem"]
          }
        ]
      },
      "then": {
        "required": ["deathAge", "deathAgeUnits", "causeDeath", "deathManner", "postmortemTox",
	             "postmortemToxSource", "medRecordTox"]
      }
    },
    {
      "if": {
        "properties": {
          "postmortem": {
            "const": "True"
          }
        }
      },
      "then": {
        "required": ["PMICertain", "PMI", "pH", "organWeight", "organRIN", "yearAutopsy"]
      }
    }, 
    {
      "if": {
        "properties": {
          "organ": {
            "const": "brain"
          }
        }
      },
      "then": {
        "required": ["BrodmannArea"]
      }
    }, 
    {
      "if": {
        "properties": {
          "assay": {
            "const": "ChIPSeq"
          }
        }
      },
      "then": {
        "required": ["assayTarget", "FRiP"]
      }
    },
    {
      "if": {
        "properties": {
          "assay": {
            "anyOf": [
              {"const": "rnaSeq"},
              {"const": "ATACSeq"}
            ]
          }
        }
      },
      "then": {
        "required": ["rRNARate", "meanCoverage", "meanGCContent"]
      }
    },
    {
      "if": {
        "properties": {
          "fileFormat": {
            "anyOf": [
              {"const": "bai"},
              {"const": "bam"}
            ]
          }
        }
      },
      "then": {
        "required": ["percentAligned", "totalReads", "mappedReads"]
      }
    }
  ]
}

=== cw-dvr8/JSON-validation-schemas/validation_schemas/psychENCODE/testfiles/psychENCODE_demo3.json
{
  "consortium": "PEC",
  "grant": "U01AG046139",
  "study": "BrainGVEX",
  "group": "JHU",
  "investigatorName": "Fernando Goes",
  "individualID": "FG-0001",
  "individualIdSource": "MSSM",
  "species": "Human",
  "reportedGender": "Unknown",
  "postmortem": "False",
  "organ": "blood",
  "specimenID": "FG-GG-BL-0001",
  "tissue": "blood",
  "cellType": "CD8+ T-Cells",
  "nucleicAcidSource": "single cell",
  "reprogrammedCellType": "T-Cell",
  "terminalDifferentiationPoint": "lsdkfj",
  "passage": 0,
  "assay": "exomeSeq",
  "libraryID": "branch-0001",
  "isStranded": true,
  "RIN": 42,
  "readLength": "longenough",
  "platform": "Illumina_1M",
  "runType": "pairedEnd",
  "libraryPrep": "rRNAdepletion",
  "libraryPreparationMethod": "10x",
  "fileFormat": "fastq",
  "referenceSet": "GRCh38",
  "readPair": 2,
  "biologicalReplicate": "F",
  "isogenicReplicate": "F",
  "anisogenicReplicate": "F",
  "technicalReplicate": "F",
  "sequencingReplicate": "F"
}

=== cw-dvr8/JSON-validation-schemas/validation_schemas/psychENCODE/testfiles/psychENCODE_demo10.json
{
  "consortium": "PEC",
  "grant": "U01AG046139",
  "study": "BrainGVEX",
  "group": "JHU",
  "investigatorName": "Fernando Goes",
  "individualID": "FG-0001",
  "individualIdSource": "MSSM",
  "species": "Human",
  "reportedGender": "Unknown",
  "postmortem": "True",
  "sex" : "male",
  "race": "Caucasian",
  "raceDetail": "Non-Hispanic",
  "genotypeInferredAncestry": "French",
  "IQ": 160,
  "BMI": 39,
  "primaryDiagnosis": "Bipolar Disorder",
  "primaryDiagnosisDetail": "Unknown at this time",
  "otherDiagnosis": "Schizophrenia",
  "otherDiagnosisDetail": "Unknown at this time",
  "familyHistory": "Unknown",
  "ageOnset": 17,
  "neuropathDescription": "None",
  "dementia": "True",
  "CDR": 2,
  "braak": 1,
  "otherMedicalDx": "Hypertension",
  "otherMedicalDetail": "Unknown at this time",
  "deathAge": 37,
  "deathAgeUnits": "years",
  "causeDeath": "Old Age",
  "deathManner": "undetermined",
  "postmortemTox": "True",
  "postmortemToxSource": "Liver",
  "medRecordTox": "False",
  "organ": "brain",
  "PMICertain": "Unknown",
  "PMI": "Yep",
  "pH": "acidic",
  "organWeight": 5,
  "organRIN": 20,
  "yearAutopsy": 2013,
  "specimenID": "FG-GG-BL-0001",
  "tissue": "blood",
  "cellType": "CD8+ T-Cells",
  "nucleicAcidSource": "single cell",
  "BrodmannArea": "BA9",
  "reprogrammedCellType": "T-Cell",
  "terminalDifferentiationPoint": "lsdkfj",
  "passage": 0,
  "assay": "ChIPSeq",
  "assayTarget": "H3K27ac",
  "libraryID": "branch-0001",
  "isStranded": true,
  "RIN": 42,
  "readLength": "longenough",
  "platform": "Illumina_1M",
  "runType": "pairedEnd",
  "libraryPrep": "rRNAdepletion",
  "libraryPreparationMethod": "10x",
  "fileFormat": "fastq",
  "referenceSet": "GRCh38",
  "readPair": 2,
  "FRiP": 29,
  "biologicalReplicate": "F",
  "isogenicReplicate": "F",
  "anisogenicReplicate": "F",
  "technicalReplicate": "F",
  "sequencingReplicate": "F"
}

=== cw-dvr8/JSON-validation-schemas/validation_schemas/psychENCODE/testfiles/psychENCODE_demo8.json
{
  "consortium": "PEC",
  "grant": "U01AG046139",
  "study": "BrainGVEX",
  "group": "JHU",
  "investigatorName": "Fernando Goes",
  "individualID": "FG-0001",
  "individualIdSource": "MSSM",
  "species": "Human",
  "reportedGender": "Unknown",
  "postmortem": "true",
  "sex" : "male",
  "race": "Caucasian",
  "raceDetail": "Non-Hispanic",
  "genotypeInferredAncestry": "French",
  "IQ": 160,
  "BMI": 39,
  "primaryDiagnosis": "Bipolar Disorder",
  "primaryDiagnosisDetail": "Unknown at this time",
  "otherDiagnosis": "Schizophrenia",
  "otherDiagnosisDetail": "Unknown at this time",
  "familyHistory": "Unknown",
  "ageOnset": 17,
  "neuropathDescription": "None",
  "dementia": true,
  "CDR": 2,
  "braak": 1,
  "otherMedicalDx": "Hypertension",
  "otherMedicalDetail": "Unknown at this time",
  "deathAge": 0,
  "deathAgeUnits": "years",
  "causeDeath": "Old Age",
  "deathManner": "Grim Reaper",
  "postmortemTox": "true",
  "postmortemToxSource": "Liver",
  "medRecordTox": "false",
  "organ": "blood",
  "PMICertain": "Unknown",
  "PMI": "Yep",
  "pH": "acidic",
  "organWeight": 0,
  "organRIN": 0,
  "yearAutopsy": 0,
  "specimenID": "FG-GG-BL-0001",
  "tissue": "blood",
  "cellType": "CD8+ T-Cells",
  "nucleicAcidSource": "single cell",
  "reprogrammedCellType": "T-Cell",
  "terminalDifferentiationPoint": "lsdkfj",
  "passage": 0,
  "assay": "exomeSeq",
  "libraryID": "branch-0001",
  "isStranded": true,
  "RIN": 42,
  "readLength": "longenough",
  "platform": "Illumina_1M",
  "runType": "pairedEnd",
  "libraryPrep": "rRNAdepletion",
  "libraryPreparationMethod": "10x",
  "fileFormat": "fastq",
  "referenceSet": "GRCh38",
  "readPair": 2,
  "biologicalReplicate": 1,
  "isogenicReplicate": 2,
  "anisogenicReplicate": 1,
  "technicalReplicate": 2,
  "sequencingReplicate": 1
}
